name: Grant roles

on:
  workflow_dispatch:

jobs:
  grant-roles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - run: npm ci --prefix js-library

      - run: npm run build --prefix js-library

      - run: npx ts-node scripts/grant-roles.ts
