name: Build and publish image

on:
  push:
    branches: [master]
    paths-ignore:
      - 'js-library/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build image
        run: ./scripts/build-image.sh

      - name: Publish image
        run: ./scripts/release-image.sh

      - name: Commit new contract metadata
        uses: EndBug/add-and-commit@v9
        with:
          author_name: CI
          author_email: actions@github.com
          message: 'build: update contract metadata'
          add: 'js-library/src/contracts/'

      # - name: Publish library
      #   run: npm run build --prefix js-library
