name: Build and publish fdp-contract blockchain image

# GH release doc https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
on:
  release:
    types: [published]
    tags-ignore:
      - fdp-contracts-js-lib*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run the environment
        run: npm run env:start-base

      - name: Build image
        run: ./scripts/build-image.sh

      - name: Publish image
        run: ./scripts/release-image.sh

      - name: Commit new contract metadata
        uses: EndBug/add-and-commit@v9
        with:
          author_name: CI
          author_email: actions@github.com
          message: 'feat(contract-upgrade): update contract metadata'
          add: 'js-library/src/contracts/'
