name: Build and publish JS library

on:
  push:
    branches:
      - master
    paths:
      - 'js-library/**'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release new NPM package'
        default: 'false'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          path: js-library
          package-name: "@fairdatasociety/fdp-contracts-js-library"
          changelog-path: 'js-library/CHANGELOG.md'
          version-file: 'js-library/package.json'

      - uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created || github.event.inputs.release == 'true' }}

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci --prefix js-library
        if: ${{ steps.release.outputs.release_created || github.event.inputs.release == 'true' }}

      - run: cd js-library && ./scripts/test.sh && cd ..
        if: ${{ steps.release.outputs.release_created || github.event.inputs.release == 'true' }}

      - run: npm run build --prefix js-library
        if: ${{ steps.release.outputs.release_created || github.event.inputs.release == 'true' }}

      - run: cd js-library && npm publish --access public && cd ..
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created || github.event.inputs.release == 'true' }}
