name: Build and publish JS library

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        if: ${{ github.event.inputs.release == 'true' }}
        id: release
        with:
          release-type: node
          path: js-library
          package-name: "@fairdatasociety/fdp-contracts-js-library"
          changelog-path: 'js-library/CHANGELOG.md'
          version-file: 'js-library/package.json'

      - uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:

      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci --prefix js-library

      - run: cd js-library && npm run ci:test && cd ..

      - run: npm run build --prefix js-library

      - run: cd js-library && npm publish --access public && cd ..
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
