name: Build and publish image

on:
  push:
    branches: [master]
    paths-ignore:
      - 'js-library/**'
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  BEE_ENV_PREFIX: 'swarm-test'
  BLOCKCHAIN_VERSION: '1.2.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          BEE_ENV_PREFIX=$(npm explore bee-factory -- ./scripts/utils/env-variable-value.sh BEE_ENV_PREFIX)
          BLOCKCHAIN_VERSION=$(npm explore bee-factory -- ./scripts/utils/env-variable-value.sh BLOCKCHAIN_VERSION)
          echo "BLOCKCHAIN_VERSION=$BLOCKCHAIN_VERSION" >> $GITHUB_ENV
          echo "BEE_ENV_PREFIX=$BEE_ENV_PREFIX" >> $GITHUB_ENV

      - name: Build image
        run: ./scripts/build-image.sh

      - name: Publish image
        run: ./scripts/release-image.sh

      - name: Commit new contract metadata
        uses: EndBug/add-and-commit@v9
        with:
          author_name: CI
          author_email: actions@github.com
          message: 'build: update contract metadata'
          add: 'js-library/src/contracts/'

      # - name: Publish library
      #   run: npm run build --prefix js-library
